# Generated by Django 3.0.3 on 2020-05-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MisCosas', '0018_auto_20200529_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='nombreAcortado',
            field=models.CharField(default='', max_length=64),
        ),
    ]
