# Generated by Django 3.0.3 on 2020-05-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MisCosas', '0019_item_nombreacortado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='nombreAcortado',
        ),
        migrations.AddField(
            model_name='alimentador',
            name='nombreAcortado',
            field=models.CharField(default='', max_length=64),
        ),
    ]
