# Generated by Django 3.0.3 on 2020-05-29 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MisCosas', '0020_auto_20200529_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimentador',
            name='nombreAcortado',
        ),
    ]
