# Generated by Django 3.0.3 on 2020-06-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MisCosas', '0024_auto_20200604_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='imagen',
            field=models.ImageField(default='', null=True, upload_to='Comments'),
        ),
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='Users'),
        ),
    ]
