# Generated by Django 3.0.3 on 2020-06-08 13:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MisCosas', '0025_auto_20200606_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 8, 13, 17, 11, 165083, tzinfo=utc)),
        ),
    ]
