# Generated by Django 3.0.3 on 2020-06-11 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MisCosas', '0027_auto_20200608_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='usuario',
        ),
    ]
